name: CI
on: [push]
jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Npm install, build
        run: npm i
        
      - name: Run ESlint
        run: npm run lint
