name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Npm install and build
        run: npm install

      - name: Run ESlint
        run: npm run lint
